[package]
name = "solana-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
futures-util = "0.3.31"

tokio = { version = "1", features = ["full"] }

solana-client = "2.1.4"
solana-sdk = "2.1.4"
solana-transaction-status = "2.1.4"
